export const FETCH_VIEW_ADMISSION_REQUEST = 'FETCH_VIEW_ADMISSION_REQUEST';
export const FETCH_VIEW_ADMISSION_SUCCESS = 'FETCH_VIEW_ADMISSION_SUCCESS';
export const FETCH_VIEW_ADMISSION_FAILURE = 'FETCH_VIEW_ADMISSION_FAILURE';
